name: ${project}

networks:
  default:
    name: ${project}
    driver: bridge
services:
  db:
    image: mariadb
    container_name: ${project}-db
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - ./db:/var/lib/mysql

  wp:
    build: ./
    container_name: ${project}-wp
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ../app:/var/www/html
      - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    ports:
      - 8080:80
